file(MAKE_DIRECTORY "${WORK_DIR}/日本語 input")
set(input_dir "${WORK_DIR}/日本語 input")
file(WRITE "${input_dir}/one.adpcm" "ABCD")
file(WRITE "${input_dir}/samples.txt" "one.adpcm\n")
set(output "${WORK_DIR}/output bank.bin")
execute_process(COMMAND "${PCMTOOL_EXE}" --list "${input_dir}/samples.txt" --output "${output}"
    RESULT_VARIABLE status OUTPUT_VARIABLE message ERROR_VARIABLE diagnostic)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "PCM CLI build failed: ${status}: ${diagnostic}")
endif()
file(SIZE "${output}" size)
file(READ "${output}" body OFFSET 1024 HEX)
if(NOT size EQUAL 1028 OR NOT body STREQUAL "41424344")
    message(FATAL_ERROR "PCM CLI output does not contain the expected bank body")
endif()
file(SHA256 "${output}" before)
execute_process(COMMAND "${PCMTOOL_EXE}" --list "${input_dir}/missing.txt" --output "${output}"
    RESULT_VARIABLE status OUTPUT_QUIET ERROR_VARIABLE diagnostic)
if(NOT status EQUAL 1 OR NOT diagnostic MATCHES "missing.txt")
    message(FATAL_ERROR "PCM CLI missing input did not report failure/path")
endif()
file(SHA256 "${output}" after)
if(NOT before STREQUAL after)
    message(FATAL_ERROR "Failed PCM CLI build changed the existing output")
endif()
execute_process(COMMAND "${PCMTOOL_EXE}" --list "${input_dir}/samples.txt" --output "${input_dir}/one.adpcm"
    RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET)
file(READ "${input_dir}/one.adpcm" sample)
if(NOT status EQUAL 1 OR NOT sample STREQUAL "ABCD")
    message(FATAL_ERROR "PCM CLI must reject overwriting an input sample")
endif()
execute_process(COMMAND "${PCMTOOL_EXE}" RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET)
if(NOT status EQUAL 2)
    message(FATAL_ERROR "PCM CLI missing arguments must return usage error 2")
endif()
execute_process(COMMAND "${PCMTOOL_EXE}" --unknown "${input_dir}" --output "${output}"
    RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET)
if(NOT status EQUAL 2)
    message(FATAL_ERROR "PCM CLI unknown input mode must return usage error 2")
endif()
